[project]
name = "contract"
version = "0.1.0"
description = "Helper contract for NEAR AI demo for UCUP 2025"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["near-sdk-py>=0.5.0"]

[project.urls]
repository = "https://github.com/frol/ucup-nearai-2025"
